(() => {
  'use strict';
  const disposers = new Map();
  const names = ['A','B','C'];
  const radians = d => d*Math.PI/180;
  const dot = (a,b) => a.reduce((s,v,i)=>s+v*b[i],0);
  const make = (tag,cls,text) => {const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
  function setup(root){
    if(root.dataset.ready)return;root.dataset.ready='true';
    const view=n=>root.querySelector(`[data-view="${n}"]`),input=n=>root.querySelector(`[data-input="${n}"]`),value=n=>root.querySelector(`[data-value="${n}"]`);
    let index=0,timer=null,observer=null;
    const action=n=>root.querySelector(`[data-action="${n}"]`);
    function stop(){if(timer!==null)clearInterval(timer);timer=null;if(action('play')){action('play').textContent='播放过程';action('play').setAttribute('aria-pressed','false')}}
    disposers.set(root,{stop,dispose:()=>{stop();if(observer)observer.disconnect()}});
    function controls(last,render){
      const refresh=()=>{render();action('prev').disabled=index===0;action('next').disabled=index===last;action('play').disabled=index===last;if(index===last)stop()};
      action('prev').onclick=()=>{stop();index=Math.max(0,index-1);refresh()};
      action('next').onclick=()=>{stop();index=Math.min(last,index+1);refresh()};
      action('reset').onclick=()=>{stop();index=0;refresh()};
      action('play').onclick=()=>{if(timer!==null){stop();return}index=Math.min(last,index+1);refresh();if(index<last){timer=setInterval(()=>{if(!root.isConnected){stop();return}index=Math.min(last,index+1);refresh()},1800);action('play').textContent='暂停';action('play').setAttribute('aria-pressed','true')}};
      refresh();return refresh;
    }
    function bars(container,items){container.replaceChildren();items.forEach(item=>{const el=make('div',item.selected?'is-selected':''),label=make('div','llm-bar-label'),name=make('span','',item.label),number=make('strong','',item.text);label.append(name,number);const track=make('div','llm-track'),fill=make('div','llm-fill');fill.style.width=item.percent+'%';track.append(fill);el.append(label,track);container.append(el)})}
    if(root.dataset.demo==='bpe'){
      const corpus=[['low',5],['lower',2],['newest',6],['widest',3]],states=[];
      let words=corpus.map(([w,count])=>({tokens:[...w],count})),previous=null;
      function pairs(ws){const map=new Map();ws.forEach(w=>{for(let i=0;i<w.tokens.length-1;i++){const pair=[w.tokens[i],w.tokens[i+1]],key=JSON.stringify(pair);if(!map.has(key))map.set(key,{pair,count:0});map.get(key).count+=w.count}});return [...map.values()].sort((a,b)=>b.count-a.count)}
      for(let n=0;n<=8;n++){const ranked=pairs(words);states.push({words:structuredClone(words),pairs:ranked,previous});if(n===8)break;const best=ranked[0];previous=best;words=words.map(w=>{const tokens=[];for(let i=0;i<w.tokens.length;i++){if(w.tokens[i]===best.pair[0]&&w.tokens[i+1]===best.pair[1]){tokens.push(best.pair.join(''));i++}else tokens.push(w.tokens[i])}return {...w,tokens}})}
      controls(8,()=>{const state=states[index];view('words').replaceChildren();state.words.forEach(w=>{const row=make('div','llm-word');row.append(make('span','llm-count','×'+w.count));w.tokens.forEach(t=>row.append(make('span','llm-symbol'+(state.previous&&t===state.previous.pair.join('')?' is-merged':''),t)));view('words').append(row)});view('pairs').replaceChildren();state.pairs.slice(0,5).forEach(p=>{const row=make('div','llm-pair');row.append(make('span','',p.pair.join(' + ')),make('span','',p.count+' 次'));view('pairs').append(row)});const total=state.words.reduce((s,w)=>s+w.tokens.length*w.count,0);view('result').textContent=`第 ${index} / 8 次合并。${state.previous?'刚刚合并 '+state.previous.pair.join(' + ')+' → '+state.previous.pair.join('')+'（原频次 '+state.previous.count+'）。':'尚未合并，从字符开始。'}语料总 token 数：${total}。当前最高频对：${state.pairs[0].pair.join(' + ')}。`});
    }
    if(root.dataset.demo==='embedding'){
      const docs=[{id:'D1',name:'网络排查',angle:10},{id:'D2',name:'设备报修',angle:45},{id:'D3',name:'电源维护',angle:80}];
      view('vectors').innerHTML=`<path class="llm-axis" d="M32 20V245H330" fill="none"/><path class="llm-axis" d="M247 245A215 215 0 0 0 32 30" fill="none"/><text x="285" y="274">维度 1</text><text x="1" y="16">维度 2</text>${docs.map(d=>{const x=32+215*Math.cos(radians(d.angle)),y=245-215*Math.sin(radians(d.angle));return `<line x1="32" y1="245" x2="${x}" y2="${y}" stroke="var(--llm-green)" stroke-dasharray="4 5"/><circle cx="${x}" cy="${y}" r="4" fill="var(--llm-green)"/><text x="${x+8}" y="${y+3}">${d.id}</text>`}).join('')}<g data-query-vector style="transform-origin:32px 245px"><line x1="32" y1="245" x2="247" y2="245" class="llm-query"/><circle cx="247" cy="245" r="5" fill="var(--llm-blue)"/></g>`;
      const items=new Map();docs.forEach(d=>{const el=make('div'),label=make('div','llm-bar-label');label.append(make('span','',d.id+' · '+d.name),make('strong'));const track=make('div','llm-track');track.append(make('div','llm-fill'));el.append(label,track);view('scores').append(el);items.set(d.id,el)});
      function render(){const a=Number(input('angle').value);value('angle').textContent=a+'°';root.querySelector('[data-query-vector]').style.transform=`rotate(${-a}deg)`;const ranking=docs.map(d=>({...d,score:Math.cos(radians(a-d.angle))})).sort((a,b)=>b.score-a.score);ranking.forEach((d,i)=>{const el=items.get(d.id);el.style.order=i;el.querySelector('strong').textContent=d.score.toFixed(4);el.querySelector('.llm-fill').style.width=d.score*100+'%'});const best=ranking.filter(d=>Math.abs(d.score-ranking[0].score)<1e-9);view('result').textContent='当前最接近：'+best.map(d=>d.id+' '+d.name).join(' / ')+(best.length>1?'（并列）':'')+'。只改变查询方向就可能改变排序；高相似度不保证文档含有答案。'}input('angle').oninput=render;render();
    }
    if(root.dataset.demo==='attention'){
      const Q=[[1,0],[0,1],[1,1]],K=Q,V=[[1,0],[0,2],[2,1]],steps=['① 点积','② 缩放','③ 遮罩','④ Softmax','⑤ 加权汇总'];
      function row(i){const raw=K.map(k=>dot(Q[i],k)),scaled=raw.map(s=>s/Math.sqrt(2)),masked=scaled.map((s,j)=>input('causal').checked&&j>i?-Infinity:s),max=Math.max(...masked),exp=masked.map(s=>Math.exp(s-max)),sum=exp.reduce((a,b)=>a+b,0),weights=exp.map(x=>x/sum),out=[0,1].map(k=>weights.reduce((s,w,j)=>s+w*V[j][k],0));return{raw,scaled,masked,weights,out}}
      const stageButtons=steps.map((s,n)=>{const b=make('button','',s);b.type='button';b.onclick=()=>{stop();index=n;refresh()};view('stages').append(b);return b});
      const cells=[];for(let i=0;i<3;i++){cells[i]=[];for(let j=0;j<3;j++){const b=make('button');b.type='button';b.onclick=()=>{stop();input('query').value=String(i);refresh()};view('matrix').append(b);cells[i][j]=b}}
      const rowItems=[];for(let j=0;j<3;j++){const el=make('div'),label=make('div','llm-bar-label');label.append(make('span','',`Key ${names[j]}`),make('strong'));const track=make('div','llm-track');track.append(make('div','llm-fill'));el.append(label,track);view('row').append(el);rowItems.push(el)}
      function render(){const selected=Number(input('query').value),r=row(selected),field=['raw','scaled','masked','weights','weights'][index];stageButtons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));view('equation').replaceChildren(root.querySelector(`[data-equation="${index}"]`).content.cloneNode(true));view('matrix-title').textContent=(index<3?'分数矩阵':'权重矩阵')+' · 行 Query / 列 Key A、B、C';for(let i=0;i<3;i++){const data=row(i)[field];for(let j=0;j<3;j++){const v=data[j],b=cells[i][j],shown=Number.isFinite(v)?v.toFixed(3):'−∞';b.textContent=shown;b.className=i===selected?'is-row':'';b.style.background=Number.isFinite(v)?`color-mix(in srgb,var(--llm-green) ${Math.round((index>=3?v:v/2)*24)}%,var(--llm-paper))`:'var(--llm-soft)';b.setAttribute('aria-pressed',String(i===selected));b.setAttribute('aria-label',`Query ${names[i]} 对 Key ${names[j]}，${shown}，选择该行`)}}r[field].forEach((n,j)=>{rowItems[j].querySelector('strong').textContent=Number.isFinite(n)?n.toFixed(4):'−∞';rowItems[j].querySelector('.llm-fill').style.width=(Number.isFinite(n)?Math.min(100,100*n/(index>=3?1:2)):0)+'%'});
        view('flow').innerHTML=[0,1,2].map(j=>{const y=25+j*48,w=r.weights[j];return `<text x="2" y="${y+4}">V${names[j]} [${V[j].join(', ')}]</text><path d="M94 ${y} Q190 ${y} 257 73" fill="none" stroke="${index===4&&w>0?'var(--llm-green)':'var(--llm-line)'}" stroke-width="${index===4?1+w*5:1}" ${index===4&&w>0?'class="llm-travel"':''}/>`}).join('')+`<circle cx="268" cy="73" r="9" fill="${index===4?'var(--llm-green)':'var(--llm-line)'}"/><text x="286" y="78">O${names[selected]}</text>`;
        const details=[`Q${names[selected]} = [${Q[selected]}]，与三个 Key 分别做点积，得到 [${r.raw.join(', ')}]。此时还不是概率。`,`每个点积除以 √2，得到 [${r.scaled.map(x=>x.toFixed(4)).join(', ')}]。只改变数值尺度。`,input('causal').checked?`位置 ${selected} 允许读取 j ≤ ${selected}；未来位置设为 −∞，保留当前位置本身。`:'关闭因果遮罩，所有三个 Key 都允许参与计算。',`沿当前 Query 行归一化，权重和 = ${r.weights.reduce((a,b)=>a+b,0).toFixed(4)}。被遮罩的位置权重为 0。`,`O${names[selected]} = ${r.weights.map((w,j)=>w.toFixed(4)+' × ['+V[j].join(', ')+']').join(' + ')} = [${r.out.map(x=>x.toFixed(4)).join(', ')}]。`];view('result').textContent=details[index];root.dataset.step=String(index);root.dataset.output=JSON.stringify(r.out)}
      const refresh=controls(4,render);input('query').onchange=()=>{stop();refresh()};input('causal').onchange=()=>{stop();refresh()};
    }
    if(root.dataset.demo==='heads'){
      function render(){const h=Number(input('heads').value),d=32/h;view('head-tiles').replaceChildren();for(let i=0;i<h;i++){const el=make('div','llm-head-tile');el.append(make('span','',`头 ${i+1}`),make('strong','',d),make('span','','维'));view('head-tiles').append(el)}view('shape-flow').replaceChildren();[['输入 / 每份投影','[2, 6, 32]'],['拆头 + transpose',`[2, ${h}, 6, ${d}]`],['QKᵀ 分数矩阵',`[2, ${h}, 6, 6]`],['每头加权结果',`[2, ${h}, 6, ${d}]`],['合并头 + 输出投影','[2, 6, 32]']].forEach(([name,shape])=>{const row=make('div','llm-shape-row');row.append(make('span','',name),make('code','',shape));view('shape-flow').append(row)});view('result').textContent=`H × dₕ = ${h} × ${d} = 32。拆头前后的 Q 元素数都是 2 × 6 × 32 = 384；显式注意力分数有 2 × ${h} × 6 × 6 = ${72*h} 个元素。固定 D 并不意味着分数矩阵体积也固定。`}input('heads').onchange=render;render();
    }
    if(root.dataset.demo==='position'){
      function render(){const pos=Number(input('position').value);value('position').textContent=pos;const width=Math.max(230,Math.round(view('waves').getBoundingClientRect().width)),height=350,left=42,right=12,plotWidth=width-left-right,x=p=>left+p/63*plotWidth,colors=['var(--llm-green)','var(--llm-blue)','var(--llm-gold)'];view('waves').setAttribute('viewBox',`0 0 ${width} ${height}`);let html='';for(let i=0;i<3;i++){const middle=54+i*99,y=v=>middle-v*25;html+=`<text x="${left}" y="${middle-36}">i = ${i} · 频率 ${Math.pow(10000,-2*i/8).toFixed(2)}</text>`;[-1,0,1].forEach(v=>{html+=`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" class="llm-axis"/><text x="12" y="${y(v)+4}">${v}</text>`});for(const [f,dash] of [[Math.sin,''],[Math.cos,'stroke-dasharray="4 4"']]){let path='';for(let p=0;p<=63;p+=.2)path+=(p===0?'M':'L')+x(p).toFixed(2)+' '+y(f(p/10000**(2*i/8))).toFixed(2)+' ';html+=`<path d="${path}" fill="none" stroke="${colors[i]}" stroke-width="1.6" ${dash}/><circle cx="${x(pos)}" cy="${y(f(pos/10000**(2*i/8)))}" r="3.5" fill="${colors[i]}"/>`}html+=`<line x1="${x(pos)}" x2="${x(pos)}" y1="${middle-29}" y2="${middle+29}" stroke="var(--llm-ink)" stroke-width="1"/>`}[0,21,42,63].forEach(p=>html+=`<text x="${x(p)}" y="315" text-anchor="${p===0?'start':p===63?'end':'middle'}">${p}</text>`);html+=`<text x="${left}" y="343">位置 pos →</text>`;view('waves').innerHTML=html;view('result').textContent=`pos=${pos} 的三对 (sin, cos)：`+[0,1,2].map(i=>{const a=pos/10000**(2*i/8);return `[${Math.sin(a).toFixed(3)}, ${Math.cos(a).toFixed(3)}]`}).join('、')+'。高频分量变化快，低频分量变化慢。'}input('position').oninput=render;observer=new ResizeObserver(()=>{if(root.isConnected)render()});observer.observe(view('waves'));render();
    }
    if(root.dataset.demo==='generation'){
      const prefix=['设备','无法','联网'],generated=['检查','网线','<EOS>'];
      controls(4,()=>{const count=Math.min(index,3),cached=index===0?0:3+Math.min(index-1,2);view('stages').replaceChildren();['准备','Prefill','Decode 1','Decode 2','停止'].forEach((s,i)=>view('stages').append(make('span','llm-stage'+(i===index?' is-active':''),s)));view('tokens').replaceChildren();prefix.concat(generated.slice(0,count)).forEach((t,i)=>view('tokens').append(make('span','llm-token'+(i>=cached&&index>0?' is-new':''),t)));view('cache').replaceChildren();if(!cached)view('cache').append(make('span','llm-empty','尚未建立缓存'));for(let i=0;i<cached;i++)view('cache').append(make('span','llm-cache-slot',`K${i} / V${i}`));const messages=['3 个已知输入 token。尚未执行前向传播，缓存为空。','同时处理 3 个输入位置，写入 K/V；最后位置的输出预测“检查”。此时缓存长度 3，序列长度 4。','把“检查”送入模型，写入新 K/V 并读取历史缓存，预测“网线”。缓存长度 4，序列长度 5。','处理“网线”，写入新 K/V，预测 <EOS>。缓存长度 5，序列长度 6。','检测到 <EOS> 后停止。无需再把 <EOS> 送入模型，因此它没有对应的已计算 K/V。'];view('result').textContent=messages[index];root.dataset.step=index;root.dataset.cached=cached});
    }
    if(root.dataset.demo==='cache'){
      function render(){const t=Number(input('length').value),b=Number(input('batch').value),h=Number(input('kv').value),s=Number(input('bytes').value),base=2*32*b*t*128*s,total=base*h;value('length').textContent=t.toLocaleString();value('batch').textContent=b;view('total').textContent=(total/2**30).toFixed(3)+' GiB';bars(view('comparison'),[1,8,32].map(k=>({label:(k===h?'● ':'')+(k===32?'MHA · 32 KV 头':k===8?'GQA · 8 KV 头':'MQA · 1 KV 头'),text:(base*k/2**30).toFixed(3)+' GiB',percent:k/32*100,selected:k===h})));view('result').textContent=`2 × 32 × ${b} × ${t} × ${h} × 128 × ${s} = ${total.toLocaleString()} 字节。当前缓存为同条件 MHA 的 ${(h/32*100).toFixed(1)}%。长度或缓存序列数翻倍，理论缓存也翻倍。`}['length','batch','kv','bytes'].forEach(n=>input(n).oninput=render);render();
    }
  }
  function init(){disposers.forEach((entry,root)=>{if(!root.isConnected){entry.dispose();disposers.delete(root)}});document.querySelectorAll('.llm-demo').forEach(setup)}
  function stopAll(){disposers.forEach(entry=>entry.stop())}
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAll()});
  document.addEventListener('pjax:send',stopAll);document.addEventListener('pjax:complete',init);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
