'use strict';
const katex = require('katex');
const math = tex => katex.renderToString(tex, {throwOnError:true,displayMode:true});
const button = (action,label) => `<button type="button" data-action="${action}">${label}</button>`;
const transport = () => `<div class="llm-controls">${button('prev','← 上一步')}${button('next','下一步 →')}${button('play','播放过程')}${button('reset','重置')}</div>`;
const range = (id,label,min,max,step,value) => `<label for="llm-${id}">${label} <output data-value="${id}">${value}</output><input id="llm-${id}" data-input="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const select = (id,label,values) => `<label for="llm-${id}">${label}<select id="llm-${id}" data-input="${id}">${values.map(([v,l,s])=>`<option value="${v}"${s?' selected':''}>${l}</option>`).join('')}</select></label>`;
const definitions = {
  bpe:{index:'01',title:'看见一个子词怎样形成',desc:'每一步都重新统计相邻符号对，再合并最高频的一对。',body:`${transport()}<div class="llm-two"><div><div class="llm-label">训练语料 · 单词及出现次数</div><div data-view="words" class="llm-word-list"></div></div><div><div class="llm-label">当前相邻符号对 · 按频次排序</div><div data-view="pairs" class="llm-pairs"></div></div></div><div data-view="result" class="llm-result" aria-live="polite"></div><p class="llm-caption">简化 BPE：low × 5、lower × 2、newest × 6、widest × 3；不跨单词合并。同频时按首次出现顺序选择，演示前 8 次合并。未使用真实模型词表。</p>`},
  embedding:{index:'02',title:'相似度是一种几何关系',desc:'拖动查询方向；改变的是夹角，文档向量保持不动。',body:`${range('angle','查询方向',0,90,1,15)}<div class="llm-two"><div><svg data-view="vectors" class="llm-svg" viewBox="0 0 350 280" role="img" aria-label="查询与三个固定文档的二维单位向量，右侧给出完整相似度数值"></svg><div class="llm-legend"><span class="llm-query-key">查询 Q</span><span>虚线：固定文档 D1 / D2 / D3</span></div></div><div data-view="scores" class="llm-ranking"></div></div><div class="llm-equation">${math(String.raw`\operatorname{sim}(q,d)=\frac{q^\top d}{\|q\|_2\|d\|_2}=\cos\theta`)}</div><div class="llm-result" data-view="result" aria-live="polite"></div><p class="llm-caption">人工构造二维向量，D1 网络排查 10°、D2 设备报修 45°、D3 电源维护 80°。图不是模型 embedding 的降维投影，轴没有预设语义。</p>`},
  attention:{index:'03',title:'把一行注意力真正算完',desc:'选择 Query，然后按步骤观察点积、缩放、遮罩、归一化与 Value 汇总。',body:`<div class="llm-controls">${select('query','Query 位置',[[0,'A · 位置 0'],[1,'B · 位置 1'],[2,'C · 位置 2']])}<label class="llm-check"><input type="checkbox" data-input="causal" checked> 因果遮罩</label></div>${transport()}<div class="llm-stages" data-view="stages"></div><div data-view="equation" class="llm-equation"></div><div class="llm-two"><div><div class="llm-label" data-view="matrix-title"></div><div data-view="matrix" class="llm-matrix" role="group" aria-label="三个 Query 对三个 Key 的计算矩阵"></div><div class="llm-caption">列为 Key A / B / C；点击单元格选择对应 Query 行。</div></div><div><div class="llm-label">当前行的可见结果</div><div data-view="row" class="llm-attn-row"></div><svg data-view="flow" class="llm-svg llm-flow" viewBox="0 0 340 152" role="img" aria-label="当前 query 从三个 Value 汇总信息"></svg></div></div><div class="llm-result" data-view="result" aria-live="polite"></div><details class="llm-details"><summary>查看这次计算的全部输入</summary><div class="llm-table"><table><thead><tr><th>位置</th><th>Q</th><th>K</th><th>V</th></tr></thead><tbody><tr><td>A</td><td>[1, 0]</td><td>[1, 0]</td><td>[1, 0]</td></tr><tr><td>B</td><td>[0, 1]</td><td>[0, 1]</td><td>[0, 2]</td></tr><tr><td>C</td><td>[1, 1]</td><td>[1, 1]</td><td>[2, 1]</td></tr></tbody></table></div></details><p class="llm-caption">Q/K/V 为手工构造，dₖ = 2。计算结果来自点积与数值稳定的 softmax，不是真实模型的注意力可视化。</p>`,equations:[String.raw`S=QK^\top`,String.raw`\widetilde S=S/\sqrt{d_k}`,String.raw`\widehat S=\widetilde S+M`,String.raw`A_{ij}=\frac{e^{\widehat S_{ij}}}{\sum_k e^{\widehat S_{ik}}}`,String.raw`O_i=\sum_j A_{ij}V_j`]},
  heads:{index:'04',title:'拆头改变了什么，没改变什么',desc:'固定 B=2、T=6、D=32。改变头数 H，沿着计算路径检查形状。',body:`<div class="llm-controls">${select('heads','注意力头数 H',[[1,'1 个头'],[2,'2 个头'],[4,'4 个头',true],[8,'8 个头']])}</div><div data-view="head-tiles" class="llm-head-tiles"></div><div data-view="shape-flow" class="llm-shape-flow"></div><div class="llm-result" data-view="result" aria-live="polite"></div><p class="llm-caption">每块代表一个头的特征通道。常规 MHA：Q/K/V 各有 H 个头；此处不模拟训练出的具体头行为。</p>`},
  position:{index:'05',title:'不同频率，共同编码一个位置',desc:'移动位置游标，同时读取三组正弦与余弦坐标。',body:`${range('position','当前位置 pos',0,63,1,8)}<svg data-view="waves" class="llm-svg" role="img" aria-label="D=8 的正弦余弦位置编码，展示 i=0、1、2 三对分量"></svg><div class="llm-result" data-view="result" aria-live="polite"></div><p class="llm-caption">按原始正弦位置编码公式计算：D=8，展示 i=0、1、2 的三对分量。实线为 sin，虚线为 cos；横轴为位置，纵轴为编码值。</p>`},
  generation:{index:'06',title:'并行读入前缀，逐次产生输出',desc:'缓存区与生成区分开显示：预测出的 token 要到下一次前向传播才写入缓存。',body:`${transport()}<div class="llm-stages" data-view="stages"></div><div class="llm-label">当前上下文 · 绿色为已缓存，蓝色为刚预测</div><div data-view="tokens" class="llm-token-stream"></div><div class="llm-label">各层 KV Cache · 这里用一行代表所有层的相同位置</div><div data-view="cache" class="llm-cache-slots"></div><div class="llm-result" data-view="result" aria-live="polite"></div><p class="llm-caption">固定的教学 token 序列，无模型调用。播放间隔仅用于阅读，不表示真实推理速度；省略 BOS、聊天模板等特殊 token。</p>`},
  cache:{index:'07',title:'让上下文成本可以计算',desc:'固定 32 层、Q 头数 32、每头 128 维；比较相同条件下不同 KV 头数。',body:`<div class="llm-two"><div class="llm-fields">${range('length','每条序列 token 数',512,32768,512,4096)}${range('batch','缓存序列数 B',1,16,1,1)}${select('kv','KV 头数',[[1,'1 · MQA'],[4,'4 · GQA'],[8,'8 · GQA',true],[32,'32 · MHA']])}${select('bytes','每元素字节',[[2,'2 · FP16 / BF16',true],[4,'4 · FP32']])}</div><div><div class="llm-label">当前理论缓存体积</div><div class="llm-big" data-view="total" aria-live="polite"></div><div data-view="comparison" class="llm-comparison"></div></div></div><div class="llm-equation">${math(String.raw`M_{\mathrm{KV}}=2LBTH_{\mathrm{KV}}d_hs`)}</div><div class="llm-result" data-view="result"></div><p class="llm-caption">同长度、完整保留历史、未压缩且未分片的缓存估算。未计权重、临时激活、碎片与服务开销；不表示整机显存需求。</p>`}
};
hexo.extend.tag.register('llm_demo', args=>{
  const type=args[0],d=definitions[type];
  if(!d)throw new Error('Unknown llm_demo: '+type);
  const eq=d.equations?d.equations.map((x,i)=>`<template data-equation="${i}">${math(x)}</template>`).join(''):'';
  return `<section class="llm-demo" data-demo="${type}" id="demo-${type}" aria-labelledby="demo-title-${type}"><div class="llm-demo-head"><span class="llm-demo-index">${d.index}</span><div><div class="llm-overline">边读边实验</div><div class="llm-demo-title" id="demo-title-${type}">${d.title}</div></div><span class="llm-live-dot" aria-hidden="true"></span></div><p class="llm-demo-desc">${d.desc}</p>${d.body}${eq}<noscript>此实验需要启用 JavaScript。正文提供对应公式与手算过程。</noscript></section>`;
});
hexo.extend.filter.register('after_post_render',data=>{
  if(data.llm_note){
    let index=0;
    data.content=data.content.replace(/(<span class="llm-demo-index">)\d+(<\/span>)/g,(_,start,end)=>start+String(++index).padStart(2,'0')+end);
    if(!data.content.startsWith('<div class="llm-note">'))data.content=`<div class="llm-note">${data.content}</div>`;
  }
  return data;
});
